language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests tests.test_amity
  - coverage run  amity.py test
after_success:
  coveralls
